export const ROUTES_DEF = {
  login: "/auth/sign-in",
  invitation: "/invitation/:token",
  loginMFA: "/auth/login-mfa",
  register: "/auth/sign-up",
  logout: "/auth/sign-out",
  mfaSetup: "/mfa/setup",
  mfaVerify: "/mfa/verify",
  home: "/dashboard",
  chats: "/dashboard/chats",
  programTemplates: "/dashboard/program-templates",
  programTemplate: "/dashboard/program-templates/:programTemplateId",
  activities: "/dashboard/activities",
  activity: "/dashboard/activities/:id",
  ads: "/dashboard/ads",
  exercises: "/dashboard/exercises",
  exercise: "/dashboard/exercises/:id",
  users: "/dashboard/users",
  user: "/dashboard/users/:id",
  patients: "/dashboard/patients",
  notifications: "/dashboard/notifications",
  admins: "/dashboard/admins",
  admin: "/dashboard/admins/:id",
  doctors: "/dashboard/doctors",
  doctor: "/dashboard/doctors/:id",
  patient: "/dashboard/patients/:id",
  me: "/dashboard/me",
  registrationRequests: "/dashboard/registration-requests",
  verification: "/dashboard/verification",
};

export const ROUTES = {
  ...ROUTES_DEF,
  programTemplate: (programTemplateId: string) =>
    ROUTES_DEF.programTemplate.replace(":programTemplateId", programTemplateId),
  activity: (id: string) => ROUTES_DEF.activity.replace(":id", id),
  exercise: (id: string) => ROUTES_DEF.exercise.replace(":id", id),
  patient: (id: string) => ROUTES_DEF.patient.replace(":id", id),
  doctor: (id: string) => ROUTES_DEF.doctors.replace(":id", id),
  user: (id: string) => ROUTES_DEF.user.replace(":id", id),
  users: (id: string) => ROUTES_DEF.users.replace(":id", id),
  admin: (id: string) => ROUTES_DEF.admin.replace(":id", id),
};
