version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "3000" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - mrs_production

  pro:
    build:
      context: .
      dockerfile: apps/pro/Dockerfile
      target: production
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mrs_production

  admin:
    build:
      context: .
      dockerfile: apps/admin/Dockerfile
      target: production
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - mrs_production

networks:
  mrs_production:
    name: mrs_production
